# Generated by Django 5.2.4 on 2025-07-19 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MigraineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "trigger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sugar", "Sugar"),
                            ("sleep", "Lack of Sleep"),
                            ("caffeine", "Caffeine"),
                            ("stress", "Stress"),
                            ("weather", "Weather Changes"),
                            ("alcohol", "Alcohol"),
                            ("dehydration", "Dehydration"),
                            ("hormones", "Hormonal Changes"),
                            ("food", "Certain Foods"),
                            ("exercise", "Overexertion"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("triggers", models.TextField(blank=True)),
                ("patterns", models.TextField(blank=True)),
                ("biorhythms", models.TextField(blank=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("severity", models.IntegerField(blank=True, default=0)),
                ("improved", models.BooleanField(default=False)),
                ("workout_time", models.DurationField(blank=True, null=True)),
                (
                    "workout_intensity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sleep_time", models.DurationField(blank=True, null=True)),
                ("screen_time", models.DurationField(blank=True, null=True)),
                ("weather_pressure", models.FloatField(blank=True, null=True)),
                ("weather_temperature", models.FloatField(blank=True, null=True)),
                ("weather_description", models.CharField(blank=True, max_length=100)),
                ("stress_level", models.IntegerField(blank=True, default=0)),
                (
                    "medications",
                    models.ManyToManyField(blank=True, to="tracker.medication"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("subscription_expiry", models.DateTimeField(blank=True, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("drinks_from_plastic", models.BooleanField(default=False)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dosage", models.CharField(blank=True, max_length=50)),
                ("timing", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileSupplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dosage", models.CharField(blank=True, max_length=50)),
                ("timing", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
