# Generated by Django 5.2.4 on 2025-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cached_weather_description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cached_weather_pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cached_weather_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_weather_fetch",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
