# Generated by Django 5.2.4 on 2025-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_userprofile_cached_weather_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migraineentry",
            name="trigger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sugar", "Sugar"),
                    ("sleep", "Lack of Sleep"),
                    ("caffeine", "Caffeine"),
                    ("stress", "Stress"),
                    ("weather", "Weather Changes"),
                    ("alcohol", "Alcohol"),
                    ("dehydration", "Dehydration"),
                    ("hormones", "Hormonal Changes"),
                    ("food", "Certain Foods (e.g., aged cheese, chocolate, MSG)"),
                    ("exercise", "Overexertion"),
                    ("skipping_meals", "Skipping Meals or Hunger"),
                    ("strong_smells", "Strong Smells (e.g., perfume, smoke)"),
                    ("bright_lights", "Bright Lights or Loud Noises"),
                    ("smoking", "Smoking"),
                    ("unknown", "Unknown"),
                ],
                max_length=50,
            ),
        ),
    ]
