# Generated by Django 5.2.4 on 2025-07-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_migraineentry_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="alcohol_frequency",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("occasional", "Occasional"),
                    ("regular", "Regular"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="caffeine_intake",
            field=models.CharField(
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="consistent_sleep",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hydration_level",
            field=models.CharField(
                choices=[("good", "Good"), ("poor", "Poor")],
                default="good",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="regular_exercise",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="smoking",
            field=models.BooleanField(default=False),
        ),
    ]
